---
sudo: required
dist: trusty

language: c

before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc doxygen graphviz

script: 
  - cd src
  - make MCU_TARGET=attiny13a F_CPU=9600000
  - make MCU_TARGET=attiny85 F_CPU=8000000
  - make clean
  # Attiny does not have a Timer1 => CPU_LOAD impossible
  - make MCU_TARGET=attiny13a F_CPU=9600000 DEBUG_ENABLE=1 CPU_LOAD=0 BAUD_RATE=57600
  - make MCU_TARGET=attiny85 F_CPU=8000000 DEBUG_ENABLE=1 CPU_LOAD=1 BAUD_RATE=57600
  - bash doc/publish_doxygen.sh
  # TODO: Upload to github pages...?