---
language: c

before_install:
  - sudo add-apt-repository ppa:pmjdebruijn/gcc-avr-release -y
  - sudo apt-get update -q
install:
  - sudo apt-get install gcc-avr-release binutils-avr avr-libc

script:
  - cd src
  - make all
